### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by SlaysGods** [seanwhos/mcoc-profile-pic#1]
Would love to see a 5-Star version - this is outstanding work and it's a huge asset to the community. Thank you!

**Comment by seanwhos** [comment]
Hi, I have no intentions of updating the site any time soon – too many real
life commitments ahead of it, one day maybe.

If you are who I think you are, judging by the name, I'm more than happy to
tidy up my Photoshop document and send you that over.

Sean

**Comment by SlaysGods** [comment]
That would be wonderful, thank you! You can reach me via email at SlayerOfGodsMCOC@gmail.com

Either way, I wanted to say thank you again for your work on the site. Myself and many others have found it tremendously helpful for a lot of things - especially content creation. I also hope it wasn't any trouble opening this "issue", it seemed like a way to submit an idea? I'm fairly new to having an account on this site and interacting haha.

Cheers!

**Comment by seanwhos** [comment]
I'm not well-versed in Github either, it was just for hosting that website
– I didn't even know people could contact me like this! Not a problem at
all though.

You're welcome, I have noticed it on many thumbnails. Feel free to share
the file with those who want it, I'll shoot it over to your other email
later today.

Cheers
